### PR TITLE
Use ruby and rails matrix in specs

### PR DESCRIPTION
**Pull request by opti**
- bump-gems-2021-07-14
- multiple ruby versions in specs
- multiple rails versions in specs

### CODE REVIEW

**Comment by madejejej** [comment]
Nice! It would also be great to run multiple Rails versions if you have the time for this. You can check out how devise-security does this: https://github.com/devise-security/devise-security/

**Review by madejejej — APPROVED** [review]
LGTM! Could you also add this change to CHANGELOG.md?

**Comment by opti** [comment]
@madejejej I'm not sure it's changelog-worthy — it only updates how we run tests, it doesn't change the functionality.

**Comment by opti** [comment]
@madejejej added multiple rails versions as well. I excluded Rails 5.2 on Ruby 3 combination since it fails due to ruby 3 syntax. I didn't dig into why exactly, rails 5.2 suppose to be supporting ruby 3, but I might be wrong here.

**Comment by madejejej** [comment]
@opti this is great, thank you!

**Pull request merged**
